# 백테스트 설정 파일 - 기본값 (현재 운영 중인 설정)
name: "default"
description: "기본 설정 (현재 운영)"

# 시간대 필터
time_filter:
  enable: true
  # 시간대별 최소 신뢰도
  hour_9_min_confidence: 70   # 09시 (승률 62.4%)
  hour_10_min_confidence: 75  # 10시 (승률 49.0%)
  hour_11_min_confidence: 75  # 11시 (승률 48.2%)
  hour_12_min_confidence: 85  # 12시 (승률 28.6%)
  hour_14_min_confidence: 85  # 14시 (승률 43.1%)
  hour_15_min_confidence: 95  # 15시 (승률 0%)

  # 완전 차단 시간대
  block_hours: []  # 예: [12, 13, 14, 15]

# 가격 필터
price_filter:
  enable: true
  min_gain_from_open_pct: 2.0   # 시가 대비 최소 상승률
  max_gain_from_open_pct: 22.0  # 시가 대비 최대 상승률

# 신뢰도 필터
confidence_filter:
  enable: true
  max_confidence: 95  # 신뢰도 상한 (과적합 방지)
  min_confidence: 70  # 신뢰도 하한

# 일봉 필터
daily_filter:
  enable: false  # 현재 비활성화
  min_strength: 40
  require_ideal_pattern: false

# 거래량 필터
volume_filter:
  enable: true
  # 돌파봉 거래량 배수 (지지 구간 평균 대비)
  breakout_volume_multiplier: 0.8  # 80% 이상

  # 지지 구간 거래량 감소 임계값
  support_volume_decline_threshold: -50  # -50% 이상 감소시 차단

# 지지 패턴 필터
support_pattern_filter:
  enable: true
  # 지지 구간 변동성 임계값
  max_support_volatility_pct: 3.0  # 3% 이상 변동성이면 차단

  # 약한 지지 조건 개수 (4개 중)
  weak_support_threshold: 2  # 2개 이상이면 차단

# 손절/익절 설정
exit_rules:
  stop_loss_pct: 2.5   # 손절 -2.5%
  take_profit_pct: 3.5  # 익절 +3.5%

# 백테스트 기간
backtest_period:
  start_date: "20250901"
  end_date: "20251029"
